name: npm build, lint, test and publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        uses: bahmutov/npm-install@v1
        with:
          args: install
      - name: npm test
        uses: bahmutov/npm-install@v1
        with:
          args: run test
      - name: npm lint
        uses: bahmutov/npm-install@v1
        with:
          args: run lint
      - name: docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: farahhachicha/GHA_3:latest
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: farahhachicha/GHA_3:latest

